### ISSUE TITLE
not able to mine.

### ISSUE THREAD

**Issue by Mbarger29** [geemcoin/Wallets#2]
I can add a mining pool but the solo mine button is ghosted out and i cant start mining. do you need a new generation processor to be able to mine? or is it Intel support only? currently trying to use a AMD Phenom II X4 965

**Comment by geemcoin** [comment]
Solo mining button will only be available when wallet is synchronized. Pool mining is not available at this time. AMD Phenom II X4 965 is an 8 years old processor. Not sure if it's going to mine or not but should work theoretically.
